{{- if and .Values.redis.enabled .Values.redis.externalName (ne (include "langgraph-primitives.isUi" .) "true") }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "langgraph-primitives.fullname" . }}-redis
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "langgraph-primitives.labels" . | nindent 4 }}
  annotations:
    langgraph/redis-db-index: {{ .Values.redis.dbIndex | default 0 | quote }}
spec:
  type: ExternalName
  externalName: {{ .Values.redis.externalName }}
  ports:
    - port: {{ .Values.redis.port | default 6379 }}
      protocol: TCP
      name: redis
{{- end }}
